<a href="https://colab.research.google.com/github/JSEFERINO/Estadistica_Moderna/blob/main/47_C_Datos_A_E_Datos_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Curso Teoría de Probabilidad por Julio Hurtado Márquez**
## **Parte XIII- Análisis Exploratorio de Datos**
# **Librerias para usar en esta parte del curso**

In [22]:
# **Librerias para usar en esta parte del cursor**
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from scipy import stats
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
from sympy.functions.combinatorial.factorials import factorial
import math
from math import sqrt
from numpy.ma.core import log
from sympy import integrate, init_printing
from sympy.abc import x
print("Setup Complete")

Setup Complete

# **207. Variables cualitativas -Tablas cruzadas - Dos Variables**

# **a. Base de datos - Una base de Datos utilizada en agricultura**
+ En esta base de Datos se tiene información de.
 - Tipos de Cultivos
 - pH
 - EC : Electroconductividad
 - Hortaliza : Parte de la planta que se consume
 - Sistema Hidroponico
 - Duración en dia
 - Costo de Producción por kilo
 - Ganancia por kilo

In [3]:
#**b. Ahora nuestra data será la copia mejorada**
datos=pd.read_csv("/content/Hidroponia_costos.csv",delimiter=',')
datos

,Cultivo,pH,EC,Hortaliza,Sistema,Duracion_Ciclo,Costo,Ganancia
0,Brocoli,6 to 6.8,2.8 to 3.5,Flor,NFT,70-90,10,29
1,Calabacita,6,1.8 to 2.4,Fruto,Goteo,45,12,33
2,Pepino,5 to 5.5,1.7 to 2,Fruto,Goteo,70-80,8,27
3,Pimientos,5.5 to 6,0.8 to 1.8,Fruto,Goteo,65,30,75
4,fresa,6,1.8 to 2.2,Fruto,NFT,120-150,55,100
5,Tomate,6 to 6.5,2 to 4,Fruto,Goteo,110-120,20,32
6,Albahaca,5.5 to 6,1 to 1.6,Hoja,NFT,90,80,150
7,Repollo,6.5 to 7,2.5 to 3,Hoja,NFT,80-100,7,19
8,Apio,6.5,1.8 to 2.4,Hoja,NFT,90-120,15,26
9,Lechuga,6 to 7,1.2 to 1.8,Hoja,NFT,80-90,10,21
10,Perejil,6 to 6.5,1.8 to 2.2,Hoja,NFT,80,45,70
11,Rabano,6 to 7,1.4 to 1.8,Raiz,Aeroponia,60-70,18,35
12,Espinacas,6 to 7,1.8 to 2.3,Hoja,NFT,75,73,160
13,Zanahoria,5.8 to 6.3,1.6 to 2.0,Raiz,Aeroponia,90-100,6,11
14,Cebollin,6.0 to 7.0,1.4 to 1.8,Tallo,NFT,120,30,75

#**b. Tablas cruzadas - Dos varibales cualitativas**
+ Analizamos las tablas cruzadas

In [6]:
pd.crosstab(datos.Hortaliza,datos.Sistema)

Sistema    Aeroponia  Goteo  NFT
Hortaliza
Flor               0      0    1
Fruto              0      4    1
Hoja               0      0    6
Raiz               2      0    0
Tallo              0      0    1

# **c. Agregamos los totales**

In [7]:
# **c. Agregamos los totales**
pd.crosstab(datos.Hortaliza,datos.Sistema, margins=True)

Sistema    Aeroponia  Goteo  NFT  All
Hortaliza
Flor               0      0    1    1
Fruto              0      4    1    5
Hoja               0      0    6    6
Raiz               2      0    0    2
Tallo              0      0    1    1
All                2      4    9   15

# **d. La misma información en porcentajes**

In [8]:
# **d. La misma información en porcentajes**
pd.crosstab(datos.Hortaliza,datos.Sistema, margins=True, normalize=True)

Sistema    Aeroponia     Goteo       NFT       All
Hortaliza
Flor        0.000000  0.000000  0.066667  0.066667
Fruto       0.000000  0.266667  0.066667  0.333333
Hoja        0.000000  0.000000  0.400000  0.400000
Raiz        0.133333  0.000000  0.000000  0.133333
Tallo       0.000000  0.000000  0.066667  0.066667
All         0.133333  0.266667  0.600000  1.000000

# **e. Normalizando las columnas**

+ Todas las hortalizas que utilizan el sistema aeroponia son del tipo raiz
+ Todas las hortalizas que utilizan el sistema Goteo son del tipo fruto
+ El sitema NFT es utilizado para cultivar Hortalizas de tipo Flor, Fruto, Hoja y Tallo

In [9]:
# **e. Normalizando las columnas**
pd.crosstab(datos.Hortaliza,datos.Sistema, normalize='columns')

Sistema    Aeroponia  Goteo       NFT
Hortaliza
Flor             0.0    0.0  0.111111
Fruto            0.0    1.0  0.111111
Hoja             0.0    0.0  0.666667
Raiz             1.0    0.0  0.000000
Tallo            0.0    0.0  0.111111

# **208. Tablas cruzadas - Tres Variables o más**

# **a. Tablas cruzadas para Tres variables**

In [10]:
# **a. Tablas cruzadas para Tres variables**
pd.crosstab([datos.Sistema,datos.Hortaliza],datos.pH)

pH                   5 to 5.5  5.5 to 6  5.8 to 6.3  6  6 to 6.5  6 to 6.8  \
Sistema   Hortaliza
Aeroponia Raiz              0         0           1  0         0         0
Goteo     Fruto             1         1           0  1         1         0
NFT       Flor              0         0           0  0         0         1
          Fruto             0         0           0  1         0         0
          Hoja              0         1           0  0         1         0
          Tallo             0         0           0  0         0         0

pH                   6 to 7  6.0 to 7.0  6.5  6.5 to 7
Sistema   Hortaliza
Aeroponia Raiz            1           0    0         0
Goteo     Fruto           0           0    0         0
NFT       Flor            0           0    0         0
          Fruto           0           0    0         0
          Hoja            2           0    1         1
          Tallo           0           1    0         0

# **b. Tablas cruzadas para cuatro variables**

In [11]:
# **b. Tablas cruzadas para cuatro variables**
pd.crosstab([datos.Sistema,datos.Hortaliza,datos.EC],datos.pH)

pH                               5 to 5.5  5.5 to 6  5.8 to 6.3  6  6 to 6.5  \
Sistema   Hortaliza EC
Aeroponia Raiz      1.4 to 1.8          0         0           0  0         0
                    1.6 to 2.0          0         0           1  0         0
Goteo     Fruto     0.8 to 1.8          0         1           0  0         0
                    1.7 to 2            1         0           0  0         0
                    1.8 to 2.4          0         0           0  1         0
                    2 to 4              0         0           0  0         1
NFT       Flor      2.8 to 3.5          0         0           0  0         0
          Fruto     1.8 to 2.2          0         0           0  1         0
          Hoja      1 to 1.6            0         1           0  0         0
                    1.2 to 1.8          0         0           0  0         0
                    1.8 to 2.2          0         0           0  0         1
                    1.8 to 2.3          0         0           0  0         0
                    1.8 to 2.4          0         0           0  0         0
                    2.5 to 3            0         0           0  0         0
          Tallo     1.4  to 1.8         0         0           0  0         0

pH                               6 to 6.8  6 to 7  6.0 to 7.0  6.5  6.5 to 7
Sistema   Hortaliza EC
Aeroponia Raiz      1.4 to 1.8          0       1           0    0         0
                    1.6 to 2.0          0       0           0    0         0
Goteo     Fruto     0.8 to 1.8          0       0           0    0         0
                    1.7 to 2            0       0           0    0         0
                    1.8 to 2.4          0       0           0    0         0
                    2 to 4              0       0           0    0         0
NFT       Flor      2.8 to 3.5          1       0           0    0         0
          Fruto     1.8 to 2.2          0       0           0    0         0
          Hoja      1 to 1.6            0       0           0    0         0
                    1.2 to 1.8          0       1           0    0         0
                    1.8 to 2.2          0       0           0    0         0
                    1.8 to 2.3          0       1           0    0         0
                    1.8 to 2.4          0       0           0    1         0
                    2.5 to 3            0       0           0    0         1
          Tallo     1.4  to 1.8         0       0           1    0         0

#**c. Tablas cruzadas para cuatro variables_ Dos en las filas y dos en las columnas**

In [13]:
#*c. Tablas cruzadas para cuatro variables_ Dos en las filas y dos en las columnas**
pd.crosstab([datos.Sistema,datos.EC],[datos.Hortaliza,datos.pH])

Hortaliza                 Flor    Fruto                          Hoja  \
pH                    6 to 6.8 5 to 5.5 5.5 to 6  6 6 to 6.5 5.5 to 6
Sistema   EC
Aeroponia 1.4 to 1.8         0        0        0  0        0        0
          1.6 to 2.0         0        0        0  0        0        0
Goteo     0.8 to 1.8         0        0        1  0        0        0
          1.7 to 2           0        1        0  0        0        0
          1.8 to 2.4         0        0        0  1        0        0
          2 to 4             0        0        0  0        1        0
NFT       1 to 1.6           0        0        0  0        0        1
          1.2 to 1.8         0        0        0  0        0        0
          1.4  to 1.8        0        0        0  0        0        0
          1.8 to 2.2         0        0        0  1        0        0
          1.8 to 2.3         0        0        0  0        0        0
          1.8 to 2.4         0        0        0  0        0        0
          2.5 to 3           0        0        0  0        0        0
          2.8 to 3.5         1        0        0  0        0        0

Hortaliza                                                Raiz         \
pH                    6 to 6.5 6 to 7 6.5 6.5 to 7 5.8 to 6.3 6 to 7
Sistema   EC
Aeroponia 1.4 to 1.8         0      0   0        0          0      1
          1.6 to 2.0         0      0   0        0          1      0
Goteo     0.8 to 1.8         0      0   0        0          0      0
          1.7 to 2           0      0   0        0          0      0
          1.8 to 2.4         0      0   0        0          0      0
          2 to 4             0      0   0        0          0      0
NFT       1 to 1.6           0      0   0        0          0      0
          1.2 to 1.8         0      1   0        0          0      0
          1.4  to 1.8        0      0   0        0          0      0
          1.8 to 2.2         1      0   0        0          0      0
          1.8 to 2.3         0      1   0        0          0      0
          1.8 to 2.4         0      0   1        0          0      0
          2.5 to 3           0      0   0        1          0      0
          2.8 to 3.5         0      0   0        0          0      0

Hortaliza                  Tallo
pH                    6.0 to 7.0
Sistema   EC
Aeroponia 1.4 to 1.8           0
          1.6 to 2.0           0
Goteo     0.8 to 1.8           0
          1.7 to 2             0
          1.8 to 2.4           0
          2 to 4               0
NFT       1 to 1.6             0
          1.2 to 1.8           0
          1.4  to 1.8          1
          1.8 to 2.2           0
          1.8 to 2.3           0
          1.8 to 2.4           0
          2.5 to 3             0
          2.8 to 3.5           0

# **209. Ejemplos de Tablas cruzadas para nuestra base de datos**

#**a. Ahora nuestra data será la copia mejorada**

In [65]:
#**a. Ahora nuestra data será la copia mejorada**
datos2=pd.read_csv("/content/df_datos_LIMPIOS2.csv",delimiter=',')
datos2

,CURSO,DEFINITIVA,PROGRAMA,EDAD,URBANO,PESO,ESTATURA,SATISFACC,SABER 11,PROMEDIO,SEXO,ESTRATO,Herramientas,Aris2,nota2
0,ESTADISTICA I,4.3,COMS,18,SI,55,164,4,350,4.26,F,II,PTWF,0,3
1,ESTADISTICA I,3.1,COMS,19,SI,65,165,5,328,4.11,F,I,CYDT,1,2
2,ESTADISTICA I,4.2,DERH,25,NO,56,170,5,285,3.70,M,I,CYDT,2,3
3,ESTADISTICA I,3.6,DERH,23,SI,65,170,5,280,4.10,F,II,PCWF,3,4
4,ESTADISTICA I,3.9,PSIC,19,SI,50,169,5,319,4.00,F,II,CYWF,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,ESTADISTICA I,3.5,PSIC,18,SI,60,163,5,310,3.90,F,III,PTWF,116,5
117,ESTADISTICA I,3.5,PSIC,18,SI,60,180,3,346,3.90,M,IV,PCWF,117,1
118,ESTADISTICA I,2.5,COMS,21,NO,45,172,5,221,3.70,F,II,CYWF,118,1
119,ESTADISTICA I,3.0,COMS,20,NO,50,160,4,332,3.50,F,II,CYDT,119,1
120,ESTADISTICA I,3.5,DERH,21,NO,57,160,4,293,3.50,F,III,PTWF,120,5

# **b. Información de nuestras columnas**

In [67]:
# **b. Información de nuestras columnas**
datos2.columns

Index(['CURSO', 'DEFINITIVA', 'PROGRAMA', 'EDAD', 'URBANO', 'PESO', 'ESTATURA',
       'SATISFACC', 'SABER 11', 'PROMEDIO', 'SEXO', 'ESTRATO', 'Herramientas',
       'Aris2', 'nota2'],
      dtype='object')

#**c. Tablas cruzadas para cuatro variables_ Dos en las filas y dos en las columnas**

In [68]:
#*c. Tablas cruzadas para cuatro variables_ Dos en las filas y dos en las columnas**
pd.crosstab([datos2.PROGRAMA,datos2.URBANO],[datos2.ESTRATO,datos2.SEXO],margins=True)

ESTRATO           I      II     III     IV     V    VI    VII  All
SEXO              F   M   F   M   F   M  F  M  F  M  F  M   M
PROGRAMA URBANO
CIENP    NO       0   2   0   0   0   1  0  0  0  0  0  0   0    3
         SI       1   1   1   1   2   3  0  0  1  0  0  1   0   11
COMS     NO       0   1   3   0   0   0  0  0  0  0  0  0   0    4
         SI       2   0   5   4   4   3  6  0  0  0  0  1   0   25
DERH     NO       3   1   0   2   1   0  0  0  0  0  0  0   0    7
         SI       1   2   3   1   1   1  0  2  0  0  0  0   0   11
ECOM     SI       0   0   1   0   0   0  0  0  0  0  0  0   0    1
FINN     NO       0   0   1   0   1   0  0  0  0  0  0  0   0    2
         SI       0   0   1   0   0   0  0  0  0  0  0  0   0    1
INAM     NO       0   0   1   0   0   0  0  0  0  0  0  0   0    1
         SI       1   0   0   0   0   0  0  0  0  0  0  0   0    1
INBM     SI       0   0   0   0   0   0  0  0  1  0  0  0   0    1
INCV     NO       1   0   0   1   0   0  0  0  0  0  0  0   0    2
         SI       0   1   0   0   0   1  0  0  0  0  0  0   1    3
ININ     NO       1   0   1   0   0   0  0  0  0  0  0  0   0    2
         SI       0   0   1   1   0   0  0  0  0  0  0  0   0    2
INMC     NO       0   1   0   1   0   1  0  0  0  0  0  0   0    3
         SI       0   0   0   0   1   2  0  0  0  0  0  0   0    3
INMT     NO       0   1   0   0   0   0  0  0  0  0  0  0   0    1
         SI       0   1   0   3   0   2  0  0  0  0  0  0   0    6
INNV     NO       0   0   0   2   0   0  0  0  0  0  0  0   0    2
         SI       0   0   0   0   0   1  0  0  0  0  0  0   0    1
INQU     SI       0   0   1   0   0   0  0  0  0  0  0  0   0    1
INST     NO       0   0   0   1   0   0  0  0  0  0  0  0   0    1
         SI       0   0   0   0   0   0  0  1  0  0  0  0   0    1
PSIC     NO       2   0   0   0   0   0  0  0  1  0  0  0   0    3
         SI       1   2   4   3   3   2  2  2  0  1  1  0   0   21
All              13  13  23  20  13  17  8  5  3  1  1  2   1  120

# **210. Tablas cruzadas para variables cuantitativas - Tablas Pivote**

# **a. Seguimos con nuestra base de datos**

In [39]:
# **a. Seguimos con nuestra base de datos**
datos

,Cultivo,pH,EC,Hortaliza,Sistema,Duracion_Ciclo,Costo,Ganancia
0,Brocoli,6 to 6.8,2.8 to 3.5,Flor,NFT,70-90,10,29
1,Calabacita,6,1.8 to 2.4,Fruto,Goteo,45,12,33
2,Pepino,5 to 5.5,1.7 to 2,Fruto,Goteo,70-80,8,27
3,Pimientos,5.5 to 6,0.8 to 1.8,Fruto,Goteo,65,30,75
4,fresa,6,1.8 to 2.2,Fruto,NFT,120-150,55,100
5,Tomate,6 to 6.5,2 to 4,Fruto,Goteo,110-120,20,32
6,Albahaca,5.5 to 6,1 to 1.6,Hoja,NFT,90,80,150
7,Repollo,6.5 to 7,2.5 to 3,Hoja,NFT,80-100,7,19
8,Apio,6.5,1.8 to 2.4,Hoja,NFT,90-120,15,26
9,Lechuga,6 to 7,1.2 to 1.8,Hoja,NFT,80-90,10,21
10,Perejil,6 to 6.5,1.8 to 2.2,Hoja,NFT,80,45,70
11,Rabano,6 to 7,1.4 to 1.8,Raiz,Aeroponia,60-70,18,35
12,Espinacas,6 to 7,1.8 to 2.3,Hoja,NFT,75,73,160
13,Zanahoria,5.8 to 6.3,1.6 to 2.0,Raiz,Aeroponia,90-100,6,11
14,Cebollin,6.0 to 7.0,1.4 to 1.8,Tallo,NFT,120,30,75

# **b. Recordemos cuales son nuestras columnas**

In [24]:
# **b. Recordemos cuales son nuestras columnas**
datos.columns

Index(['Cultivo', 'pH', 'EC', 'Hortaliza', 'Sistema', 'Duracion_Ciclo',
       'Costo', 'Ganancia'],
      dtype='object')

# **c. Tablas Pivote - Datos Numericos**
+ Una variable cualitativa con dos variables cuantitativas

In [25]:
# **c. Tablas Pivote - Datos Numericos**
# Para lashortalizas se realizan las ganancias y los costos
datos.pivot_table(index = 'Sistema', values=['Costo', 'Ganancia'], aggfunc=np.sum)

           Costo  Ganancia
Sistema
Aeroponia     24        46
Goteo         70       167
NFT          325       650

# **b. Datos marginales -Para las hortalizas se realizan las ganancias y los costos**

In [27]:
# **b. Datos marginales -Para las hortalizas se realizan las ganancias y los costos**
datos.pivot_table(index = 'Sistema', values=['Costo', 'Ganancia'], margins=True, aggfunc=np.sum)

           Costo  Ganancia
Sistema
Aeroponia     24        46
Goteo         70       167
NFT          325       650
All          419       863

# **c. Promedios Datos marginales -Para las hortalizas se realizan las ganancias y los costos**

In [28]:
# **c. Promedios Datos marginales -Para las hortalizas se realizan las ganancias y los costos**
datos.pivot_table(index = 'Sistema', values=['Costo', 'Ganancia'], margins=True, aggfunc=np.mean)

               Costo   Ganancia
Sistema
Aeroponia  12.000000  23.000000
Goteo      17.500000  41.750000
NFT        36.111111  72.222222
All        27.933333  57.533333

# **d. Redondeo de Promedios Datos marginales -Para las hortalizas se realizan las ganancias y los costos**

In [29]:
# **d. Redondeo de Promedios Datos marginales -Para las hortalizas se realizan las ganancias y los costos**
round(datos.pivot_table(index = 'Sistema', values=['Costo', 'Ganancia'], margins=True, aggfunc=np.mean),2)

           Costo  Ganancia
Sistema
Aeroponia  12.00     23.00
Goteo      17.50     41.75
NFT        36.11     72.22
All        27.93     57.53

# **e. Dos variables cualitativas y una cuantitativa**

In [30]:
# **e. Dos variables cualitativas y una cuantitativa**
datos.pivot_table(index = ['Sistema','Hortaliza'], values=['Costo'], margins=True, aggfunc=np.sum)

                     Costo
Sistema   Hortaliza
Aeroponia Raiz          24
Goteo     Fruto         70
NFT       Flor          10
          Fruto         55
          Hoja         230
          Tallo         30
All                    419

# **f. Tres variables cualitativas y una cuantitativa**

In [31]:
# **f. Tres variables cualitativas y una cuantitativa**
datos.pivot_table(index = ['Sistema','Hortaliza'], values=['Costo'], columns =['pH'], margins=True, aggfunc=np.sum)

                       Costo                                              \
pH                  5 to 5.5 5.5 to 6 5.8 to 6.3     6 6 to 6.5 6 to 6.8
Sistema   Hortaliza
Aeroponia Raiz           NaN      NaN        6.0   NaN      NaN      NaN
Goteo     Fruto          8.0     30.0        NaN  12.0     20.0      NaN
NFT       Flor           NaN      NaN        NaN   NaN      NaN     10.0
          Fruto          NaN      NaN        NaN  55.0      NaN      NaN
          Hoja           NaN     80.0        NaN   NaN     45.0      NaN
          Tallo          NaN      NaN        NaN   NaN      NaN      NaN
All                      8.0    110.0        6.0  67.0     65.0     10.0


pH                  6 to 7 6.0 to 7.0   6.5 6.5 to 7  All
Sistema   Hortaliza
Aeroponia Raiz        18.0        NaN   NaN      NaN   24
Goteo     Fruto        NaN        NaN   NaN      NaN   70
NFT       Flor         NaN        NaN   NaN      NaN   10
          Fruto        NaN        NaN   NaN      NaN   55
          Hoja        83.0        NaN  15.0      7.0  230
          Tallo        NaN       30.0   NaN      NaN   30
All                  101.0       30.0  15.0      7.0  419

# **g. Tres variables cualitativas y una cuantitativa - Elimanos la posición sin información**

In [32]:
# **g. Tres variables cualitativas y una cuantitativa - Elimanos la posición sin información**
datos.pivot_table(index = ['Sistema','Hortaliza'], values=['Costo'], columns =['pH'], margins=True, aggfunc=np.sum,
                  fill_value=0)

                       Costo                                                   \
pH                  5 to 5.5 5.5 to 6 5.8 to 6.3   6 6 to 6.5 6 to 6.8 6 to 7
Sistema   Hortaliza
Aeroponia Raiz             0        0          6   0        0        0     18
Goteo     Fruto            8       30          0  12       20        0      0
NFT       Flor             0        0          0   0        0       10      0
          Fruto            0        0          0  55        0        0      0
          Hoja             0       80          0   0       45        0     83
          Tallo            0        0          0   0        0        0      0
All                        8      110          6  67       65       10    101


pH                  6.0 to 7.0 6.5 6.5 to 7  All
Sistema   Hortaliza
Aeroponia Raiz               0   0        0   24
Goteo     Fruto              0   0        0   70
NFT       Flor               0   0        0   10
          Fruto              0   0        0   55
          Hoja               0  15        7  230
          Tallo             30   0        0   30
All                         30  15        7  419

# **h. Multiples variables cualitativas y una cuantitativa**

In [38]:
# **h. Multiples variables cualitativas y una cuantitativa**
datos.pivot_table(index = 'Hortaliza', values=['Costo'], columns =['Sistema'],
                  aggfunc={'Costo':[np.sum, np.mean],'Sistema': len},
                  fill_value=0)

              Costo                                         Sistema
               mean                        sum                  len
Sistema   Aeroponia Goteo        NFT Aeroponia Goteo  NFT Aeroponia Goteo NFT
Hortaliza
Flor              0   0.0  10.000000         0     0   10         0     0   1
Fruto             0  17.5  55.000000         0    70   55         0     4   1
Hoja              0   0.0  38.333333         0     0  230         0     0   6
Raiz             12   0.0   0.000000        24     0    0         2     0   0
Tallo             0   0.0  30.000000         0     0   30         0     0   1

# **i. Multiples variables cualitativas y una cuantitativa - Redondeo**

In [40]:
# **i. Multiples variables cualitativas y una cuantitativa - Redondeo**
round(datos.pivot_table(index = 'Hortaliza', values=['Costo'], columns =['Sistema'],
                  aggfunc={'Costo':[np.sum, np.mean],'Sistema': len},
                  fill_value=0),2)

              Costo                                     Sistema
               mean                    sum                  len
Sistema   Aeroponia Goteo    NFT Aeroponia Goteo  NFT Aeroponia Goteo NFT
Hortaliza
Flor              0   0.0  10.00         0     0   10         0     0   1
Fruto             0  17.5  55.00         0    70   55         0     4   1
Hoja              0   0.0  38.33         0     0  230         0     0   6
Raiz             12   0.0   0.00        24     0    0         2     0   0
Tallo             0   0.0  30.00         0     0   30         0     0   1

# **211. Ejemplos con nuestra base de Datos**

In [69]:
# nuestros datos
datos2.columns

Index(['CURSO', 'DEFINITIVA', 'PROGRAMA', 'EDAD', 'URBANO', 'PESO', 'ESTATURA',
       'SATISFACC', 'SABER 11', 'PROMEDIO', 'SEXO', 'ESTRATO', 'Herramientas',
       'Aris2', 'nota2'],
      dtype='object')

In [70]:
# Tabla Pivot**
datos2.pivot_table(index = 'PROGRAMA', values=['DEFINITIVA'], columns =['SEXO'],
                  aggfunc={'DEFINITIVA':[np.mean,np.std],'SEXO': len},
                  fill_value=0)

         DEFINITIVA                               SEXO
               mean                 std            len
SEXO              F         M         F         M    F   M
PROGRAMA
CIENP      4.060000  4.000000  0.598331  0.509902    5   9
COMS       3.740000  3.233333  1.018461  0.692820   20   9
DERH       3.888889  3.688889  0.491031  0.754063    9   9
ECOM       2.500000  0.000000  0.000000  0.000000    1   0
FINN       5.000000  0.000000  0.000000  0.000000    3   0
INAM       4.750000  0.000000  0.353553  0.000000    2   0
INBM       4.300000  0.000000  0.000000  0.000000    1   0
INCV       5.000000  4.125000  0.000000  0.478714    1   4
ININ       4.566667  3.300000  0.208167  0.000000    3   1
INMC       4.500000  3.980000  0.000000  0.342053    1   5
INMT       0.000000  4.157143  0.000000  0.799702    0   7
INNV       0.000000  4.100000  0.000000  0.964365    0   3
INQU       3.900000  0.000000  0.000000  0.000000    1   0
INST       0.000000  4.000000  0.000000  0.000000    0   2
PSIC       3.266667  3.170000  0.880476  1.168142   15  10

In [71]:
round(datos2.pivot_table(index = 'PROGRAMA', values=['DEFINITIVA'], columns =['SEXO'],
                  aggfunc={'DEFINITIVA':[np.std, np.mean],'SEXO': len},
                  fill_value=0),2)

         DEFINITIVA                   SEXO
               mean         std        len
SEXO              F     M     F     M    F   M
PROGRAMA
CIENP          4.06  4.00  0.60  0.51    5   9
COMS           3.74  3.23  1.02  0.69   20   9
DERH           3.89  3.69  0.49  0.75    9   9
ECOM           2.50  0.00  0.00  0.00    1   0
FINN           5.00  0.00  0.00  0.00    3   0
INAM           4.75  0.00  0.35  0.00    2   0
INBM           4.30  0.00  0.00  0.00    1   0
INCV           5.00  4.12  0.00  0.48    1   4
ININ           4.57  3.30  0.21  0.00    3   1
INMC           4.50  3.98  0.00  0.34    1   5
INMT           0.00  4.16  0.00  0.80    0   7
INNV           0.00  4.10  0.00  0.96    0   3
INQU           3.90  0.00  0.00  0.00    1   0
INST           0.00  4.00  0.00  0.00    0   2
PSIC           3.27  3.17  0.88  1.17   15  10

In [76]:
round(datos2.pivot_table(index = ['PROGRAMA','URBANO'], values=['DEFINITIVA'], columns =['SEXO'],
                  aggfunc={'DEFINITIVA':[np.std, np.mean],'SEXO': len},
                  fill_value=0),2)

                DEFINITIVA                   SEXO
                      mean         std        len
SEXO                     F     M     F     M    F   M
PROGRAMA URBANO
CIENP    NO           0.00  3.83  0.00  0.35    0   3
         SI           4.06  4.08  0.60  0.58    5   6
COMS     NO           3.33  2.50  1.04  0.00    3   1
         SI           3.81  3.32  1.03  0.68   17   8
DERH     NO           3.80  3.87  0.36  0.58    4   3
         SI           3.96  3.60  0.61  0.86    5   6
ECOM     SI           2.50  0.00  0.00  0.00    1   0
FINN     NO           5.00  0.00  0.00  0.00    2   0
         SI           5.00  0.00  0.00  0.00    1   0
INAM     NO           4.50  0.00  0.00  0.00    1   0
         SI           5.00  0.00  0.00  0.00    1   0
INBM     SI           4.30  0.00  0.00  0.00    1   0
INCV     NO           5.00  4.50  0.00  0.00    1   1
         SI           0.00  4.00  0.00  0.50    0   3
ININ     NO           4.45  0.00  0.07  0.00    2   0
         SI           4.80  3.30  0.00  0.00    1   1
INMC     NO           0.00  4.03  0.00  0.25    0   3
         SI           4.50  3.90  0.00  0.57    1   2
INMT     NO           0.00  4.00  0.00  0.00    0   1
         SI           0.00  4.18  0.00  0.87    0   6
INNV     NO           0.00  3.75  0.00  1.06    0   2
         SI           0.00  4.80  0.00  0.00    0   1
INQU     SI           3.90  0.00  0.00  0.00    1   0
INST     NO           0.00  4.00  0.00  0.00    0   1
         SI           0.00  4.00  0.00  0.00    0   1
PSIC     NO           3.25  0.00  0.65  0.00    4   0
         SI           3.27  3.17  0.98  1.17   11  10