<a href="https://colab.research.google.com/github/JSEFERINO/Estadistica_Moderna/blob/main/75_C_Datos_DOE2FAC_Manual.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  **Tema 6: Diseño Factorial -Dos Factores usando Python**
# **a. El Problema**
##  **Ejemplo de un Diseño Factorial $4\bigotimes3$**.

### **Consideremos un experimento en el que se quiere estudiar el efecto de los factores velocidad de alimentación y profundidad de corte sobre el acabado de un metal. Aunque los factores son de naturaleza continua, en este proceso sólo se pueden trabajar en 3 y 4 niveles, respectivamente. Por ello, se decide correr un factorial completo $4\bigotimes3$ con tres réplicas, que permitirá obtener toda la información relevante en relación al efecto de estos factores sobre el acabado. Aleatorizando las 36 pruebas se obtienen los datos en la tabla siguiente. El acabado ($Y$) está en unidades de gramos e interesa minimizar su valor.**

|B: Velocidad \ A: Profundidad|	0.15	|0.18	|0.21	|0.24|
|:--:|:--:|:--:|:--:|:--:|
|0.20	|74, 64, 60|	79, 68, 73|	82, 88, 92|	99, 104, 96|
|0.25	|92, 86, 88|	98, 104, 88|	99, 108, 95|	104, 110, 99|
|0.30	|99, 98, 102|	104, 99, 95	|108, 110, 99|	114, 111, 107|

## **Paso_1. Ingresamos los datos manual**

## **a. Nuestros datos**

In [129]:
import pandas as pd

In [130]:
## **4.1 Los Datos del Problema**
N = 36; I = 4; J = 3; n = 3
Profundidad  =  (['A1']*3+['A2']*3+['A3']*3+['A4']*3)*3
Velocidad  =  ['B1']*12+['B2']*12+['B3']*12

Acabado =[74, 64, 60, 79, 68, 73, 82, 88, 92, 99, 104, 96, 92,
          86, 88,	98, 104, 88,	99, 108, 95,	104, 110, 99, 99,
          98, 102,	104, 99, 95,	108, 110, 99,	114, 111, 107]

## **b. El DataFrame**

In [131]:
## **b. El DataFrame**
df = pd.DataFrame({'Velocidad':Velocidad, 'Profundidad':Profundidad, 'Acabado':Acabado})
df.head()

  Velocidad Profundidad  Acabado
0        B1          A1       74
1        B1          A1       64
2        B1          A1       60
3        B1          A2       79
4        B1          A2       68

## **c. Preguntando por un nivel de un factor**

In [132]:
df[(df["Velocidad"]=="B1")]

   Velocidad Profundidad  Acabado
0         B1          A1       74
1         B1          A1       64
2         B1          A1       60
3         B1          A2       79
4         B1          A2       68
5         B1          A2       73
6         B1          A3       82
7         B1          A3       88
8         B1          A3       92
9         B1          A4       99
10        B1          A4      104
11        B1          A4       96

## **d. Preguntando por una combinación de niveles**

In [133]:
df[(df["Velocidad"]=="B1") & (df["Profundidad"]=="A1")]

  Velocidad Profundidad  Acabado
0        B1          A1       74
1        B1          A1       64
2        B1          A1       60

## **e. Preguntando por un medidad de un nivel de un factor**

In [134]:
df[(df["Velocidad"]=="B1")].sum()

Velocidad      B1B1B1B1B1B1B1B1B1B1B1B1
Profundidad    A1A1A1A2A2A2A3A3A3A4A4A4
Acabado                             979
dtype: object

## **e. Preguntando por un medida de una combinación de niveles**

In [135]:
df[(df["Velocidad"]=="B1") & (df["Profundidad"]=="A1")].sum()

Velocidad      B1B1B1
Profundidad    A1A1A1
Acabado           198
dtype: object

In [136]:
df[(df["Profundidad"]=="A2")].sum()

Velocidad      B1B1B1B2B2B2B3B3B3
Profundidad    A2A2A2A2A2A2A2A2A2
Acabado                       808
dtype: object

# **Paso_2. Extremos las mediciones para el Anove**

## **a. Eligiendo la forma de extraer la medida**

In [137]:
Velocidad, Profundidad, sum_B1 = (df[(df["Velocidad"]=="B1")].sum())
sum_B1

979

## **b. Hallamos los totales por niveles de cada factor**

In [174]:
Velocidad, Profundidad, sum_B1  = df[(df["Velocidad"]=="B1")].sum()
Velocidad, Profundidad, sum_B2  = df[(df["Velocidad"]=="B2")].sum()
Velocidad, Profundidad, sum_B3 = df[(df["Velocidad"]=="B3")].sum()
Velocidad, Profundidad, sum_A1 = df[(df["Profundidad"]=="A1")].sum()
Velocidad, Profundidad, sum_A2 = df[(df["Profundidad"]=="A2")].sum()
Velocidad, Profundidad, sum_A3 = df[(df["Profundidad"]=="A3")].sum()
Velocidad, Profundidad, sum_A4 = df[(df["Profundidad"]=="A4")].sum()
sum_T = sum_A1+sum_A2+sum_A3+sum_A4
sum_A = sum_A1+sum_A2+sum_A3+sum_A4
sum_B = sum_B1+sum_B2+sum_B3
sum_A22 = sum_A1**2+sum_A2**2+sum_A3**2+sum_A4**2
sum_B22 = sum_B1**2+sum_B2**2+sum_B3**2

## **c. Construimos la Tabla para la informacion**

In [139]:
!pip install texttable

Requirement already satisfied: texttable in /usr/local/lib/python3.10/dist-packages (1.6.7)

In [193]:
from texttable import Texttable
t1 = Texttable()
t1.add_rows([['Estadistico','Suma','media', 'Total^2' ],
           ['sum_B1',	sum_B1,sum_B1/12,	sum_B1**2],
           ['sum_B2',	sum_B2,sum_B2/12,	sum_B2**2],
           ['sum_B3',	sum_B3,sum_B3/12,	sum_B3**2],
           ['sum_A1',	sum_A1,sum_A1/9,	sum_A1**2],
           ['sum_A2',	sum_A2,	sum_A2/9, sum_A2**2],
           ['sum_A3',	sum_A3,	sum_A3/9, sum_A3**2],
           ['sum_A4',	sum_A4,	sum_A4/9, sum_A4**2],
           ['sum_T',	sum_T,	sum_T/36, sum_T**2],
           ['sum_A22',	'',	'',	sum_A22],
           ['sum_B22',	'',	'',	sum_B22]])
print(t1.draw())

+-------------+------+---------+----------+
| Estadistico | Suma |  media  | Total^2  |
+=============+======+=========+==========+
| sum_B1      | 979  | 81.583  | 958441   |
+-------------+------+---------+----------+
| sum_B2      | 1171 | 97.583  | 1371241  |
+-------------+------+---------+----------+
| sum_B3      | 1246 | 103.833 | 1552516  |
+-------------+------+---------+----------+
| sum_A1      | 763  | 84.778  | 582169   |
+-------------+------+---------+----------+
| sum_A2      | 808  | 89.778  | 652864   |
+-------------+------+---------+----------+
| sum_A3      | 881  | 97.889  | 776161   |
+-------------+------+---------+----------+
| sum_A4      | 944  | 104.889 | 891136   |
+-------------+------+---------+----------+
| sum_T       | 3396 | 94.333  | 11532816 |
+-------------+------+---------+----------+
| sum_A22     |      |         | 2902330  |
+-------------+------+---------+----------+
| sum_B22     |      |         | 3882198  |
+-------------+------+---------+----------+

# **e. Lo mismo para las Combinaciones y las mediciones al cuadrado**

In [176]:
Velocidad, Profundidad, sum_A1B1  = df[(df["Velocidad"]=="B1") & (df["Profundidad"]=="A1")].sum()
Velocidad, Profundidad, sum_A1B2  = df[(df["Velocidad"]=="B2") & (df["Profundidad"]=="A1")].sum()
Velocidad, Profundidad, sum_A1B3  = df[(df["Velocidad"]=="B3") & (df["Profundidad"]=="A1")].sum()
Velocidad, Profundidad, sum_A2B1  = df[(df["Velocidad"]=="B1") & (df["Profundidad"]=="A2")].sum()
Velocidad, Profundidad, sum_A2B2  = df[(df["Velocidad"]=="B2") & (df["Profundidad"]=="A2")].sum()
Velocidad, Profundidad, sum_A2B3  = df[(df["Velocidad"]=="B3") & (df["Profundidad"]=="A2")].sum()
Velocidad, Profundidad, sum_A3B1  = df[(df["Velocidad"]=="B1") & (df["Profundidad"]=="A3")].sum()
Velocidad, Profundidad, sum_A3B2  = df[(df["Velocidad"]=="B2") & (df["Profundidad"]=="A3")].sum()
Velocidad, Profundidad, sum_A3B3  = df[(df["Velocidad"]=="B3") & (df["Profundidad"]=="A3")].sum()
Velocidad, Profundidad, sum_A4B1  = df[(df["Velocidad"]=="B1") & (df["Profundidad"]=="A4")].sum()
Velocidad, Profundidad, sum_A4B2  = df[(df["Velocidad"]=="B2") & (df["Profundidad"]=="A4")].sum()
Velocidad, Profundidad, sum_A4B3  = df[(df["Velocidad"]=="B3") & (df["Profundidad"]=="A4")].sum()
sum_AB2 = sum_A1B1**2 + sum_A1B2**2 + sum_A1B3**2 + sum_A2B1**2 + sum_A2B2**2 + sum_A2B3**2 + sum_A3B1**2 + sum_A3B2**2 + sum_A3B3**2 + sum_A4B1**2 + sum_A4B2**2 + sum_A4B3**2
sum_Y2 = (df["Acabado"]*df["Acabado"]).sum()

In [177]:
t2 = Texttable()
t2.add_rows([['Suma','Suma_AB', 'Suma_AB^2' ],
           ['sum_A1B1',	sum_A1B1,	sum_A1B1**2],
           ['sum_A1B2',	sum_A1B2,	sum_A1B2**2],
           ['sum_A1B3',	sum_A1B3,	sum_A1B3**2],
           ['sum_A2B1',	sum_A2B1,	sum_A2B1**2],
           ['sum_A2B2',	sum_A2B2,	sum_A2B2**2],
           ['sum_A2B3',	sum_A2B3,	sum_A2B3**2],
           ['sum_A3B1',	sum_A3B1,	sum_A3B1**2],
           ['sum_A3B2',	sum_A3B2,	sum_A3B2**2],
           ['sum_A3B3',	sum_A3B3,	sum_A3B3**2],
           ['sum_A4B1',	sum_A3B1,	sum_A3B1**2],
           ['sum_A4B2',	sum_A3B2,	sum_A3B2**2],
           ['sum_A4B3',	sum_A3B3,	sum_A3B3**2],
           ['sum_AB2',	sum_AB2,	''],
           ['sum_Y2',	sum_Y2,	'']  ])
print(t2.draw())

+----------+---------+-----------+
|   Suma   | Suma_AB | Suma_AB^2 |
+==========+=========+===========+
| sum_A1B1 | 198     | 39204     |
+----------+---------+-----------+
| sum_A1B2 | 266     | 70756     |
+----------+---------+-----------+
| sum_A1B3 | 299     | 89401     |
+----------+---------+-----------+
| sum_A2B1 | 220     | 48400     |
+----------+---------+-----------+
| sum_A2B2 | 290     | 84100     |
+----------+---------+-----------+
| sum_A2B3 | 298     | 88804     |
+----------+---------+-----------+
| sum_A3B1 | 262     | 68644     |
+----------+---------+-----------+
| sum_A3B2 | 302     | 91204     |
+----------+---------+-----------+
| sum_A3B3 | 317     | 100489    |
+----------+---------+-----------+
| sum_A4B1 | 262     | 68644     |
+----------+---------+-----------+
| sum_A4B2 | 302     | 91204     |
+----------+---------+-----------+
| sum_A4B3 | 317     | 100489    |
+----------+---------+-----------+
| sum_AB2  | 978596  |           |
+----------+---------+-----------+
| sum_Y2   | 326888  |           |
+----------+---------+-----------+

# **Paso_3. Variabilidad Total y Varianza Total**

## **a. La variabilidad total es _SST_ y la Varianza Total _CMT_**

In [178]:
## **b. La variabilidad total es _SST_ y la Varianza Total _CMT_**
SST = sum_Y2 - sum_T**2/N
MST = SST/(N-1)
print(f'La variabilidad total es SST = {SST}')
print(f'La Varianza total es MST = {MST}')

La variabilidad total es SST = 6532.0
La Varianza total es MST = 186.62857142857143

## **b. La variabilidad de los Tratamientos es _SSTr_ y la Varianza Total _CMTr_**

In [181]:
## **c. La variabilidad de los Tratamientos es _SSTr_ y la Varianza Total _CMTr_
SSA = sum_A22/(n*J) - sum_T**2/N

MSA = SSA/(I-1)
print(f'La variabilidad de los tratamientos es SSA = {SSA}')
print(f'La variabilidad de los tratamientos es MSA = {MSA}')

La variabilidad de los tratamientos es SSA = 2125.111111111124
La variabilidad de los tratamientos es MSA = 708.3703703703746

In [182]:
## **c. La variabilidad de los Tratamientos es _SSTr_ y la Varianza Total _CMTr_
SSB = sum_B22/(n*I) - sum_T**2/N

MSB = SSB/(J-1)
print(f'La variabilidad de los tratamientos es SSB = {SSB}')
print(f'La variabilidad de los tratamientos es MSB = {MSB}')

La variabilidad de los tratamientos es SSB = 3160.5
La variabilidad de los tratamientos es MSB = 1580.25

In [183]:
## **c. La variabilidad de los Tratamientos es _SSTr_ y la Varianza Total _CMTr_
SSAB = sum_AB2/n - sum_T**2/N-SSA-SSB

MSAB = SSAB/((I-1)*(J-1))
print(f'La variabilidad de los tratamientos es SSAB = {SSAB}')
print(f'La variabilidad de los tratamientos es MSAB = {MSAB}')

La variabilidad de los tratamientos es SSAB = 557.055555555562
La variabilidad de los tratamientos es MSAB = 92.84259259259368

## **c. La variabilidad de los Residuos es _SSE_ y la Varianza Total _CME_**

In [184]:
SSE = SST - SSA - SSB - SSAB

MSE = SSE/(I*J*(n-1))
print(f'La variabilidad de los residuos es SSE = {SSE}')
print(f'La varianza de los residuos es MSE = {MSE}')

La variabilidad de los residuos es SSE = 689.3333333333139
La varianza de los residuos es MSE = 28.722222222221415

## **d. El coeficiente de determinación del ajuste**

$$R^2 = 1- \frac{SSE}{SST}$$

In [185]:
R_2 = 1- SSE/SST
print(f'El coeficente de R_cuadrado es {R_2*100} por ciento')

El coeficente de R_cuadrado es 89.44682588283352 por ciento

## **e. Instalando La librería Necesaria _texttable_**

In [149]:
!pip install texttable

Requirement already satisfied: texttable in /usr/local/lib/python3.10/dist-packages (1.6.7)

## **f. El valor p, de la prueba**

In [186]:
from scipy import stats
F1 = stats.f(I-1,I*J*(n-1))
F2 = stats.f(J-1,I*J*(n-1))
F3 = stats.f((I-1)*(J-1),I*J*(n-1))
valor_p1 = 1 - F1.cdf(MSA/MSE)
valor_p2 = 1 - F2.cdf(MSB/MSE)
valor_p3 = 1 - F3.cdf(MSAB/MSE)

## **g. Construyendo la Tabla Anova**

In [187]:
from texttable import Texttable
t3 = Texttable()
t3.add_rows([['Fuente','SS', 'g.l', 'MS', 'F', 'valor_p'],
           ['A',	SSA,	I-1,	MSA,	MSA/MSE, valor_p1],
           ['B',	SSB,	J-1,	MSB,	MSB/MSE, valor_p2],
           ['AB',	SSAB,	(I-1)*(J-1),	MSAB,	MSAB/MSE, valor_p3],
           ['Error',	SSE,	I*J*(n-1),	MSE, '', ''],
           ['Total',	SST,	N-1, '' , '', '']])
print(t3.draw())

+--------+----------+-----+----------+--------+---------+
| Fuente |    SS    | g.l |    MS    |   F    | valor_p |
+========+==========+=====+==========+========+=========+
| A      | 2125.111 | 3   | 708.370  | 24.663 | 0.000   |
+--------+----------+-----+----------+--------+---------+
| B      | 3160.500 | 2   | 1580.250 | 55.018 | 0.000   |
+--------+----------+-----+----------+--------+---------+
| AB     | 557.056  | 6   | 92.843   | 3.232  | 0.018   |
+--------+----------+-----+----------+--------+---------+
| Error  | 689.333  | 24  | 28.722   |        |         |
+--------+----------+-----+----------+--------+---------+
| Total  | 6532     | 35  |          |        |         |
+--------+----------+-----+----------+--------+---------+

# **h. Prueba de Tukey**

- $$Tukey_A = Q_{α=0.05,I,IJ(n-1)}\sqrt{\frac{CME}{nJ}}  $$

- $$Tukey_B = Q_{α=0.05,J,IJ(n-1)}\sqrt{\frac{CME}{nI}}  $$

In [152]:
TUKEY=pd.read_csv("/content/TUKEY_TABLA.csv",delimiter=';', index_col=0)
TUKEY

,2,3,4,5,6,7,8,9,10,11,...,21,22,23,24,25,26,27,28,29,30
2.0,6.08,8.33,9.80,10.88,11.73,12.43,13.03,13.54,13.99,14.40,...,16.97,17.14,17.30,17.46,17.61,17.75,17.88,18.01,18.13,18.25
3.0,4.50,5.91,6.82,7.50,8.04,8.48,8.85,9.18,9.46,9.72,...,11.36,11.47,11.58,11.68,11.78,11.87,11.96,12.05,12.13,12.21
4.0,3.93,5.04,5.76,6.29,6.71,7.05,7.35,7.60,7.83,8.03,...,9.33,9.42,9.50,9.58,9.66,9.74,9.81,9.88,9.94,10.00
5.0,3.64,4.60,5.22,5.67,6.03,6.33,6.58,6.80,6.99,7.17,...,8.29,8.37,8.44,8.51,8.58,8.64,8.70,8.76,8.82,8.87
6.0,3.46,4.34,4.90,5.30,5.63,5.90,6.12,6.32,6.49,6.65,...,7.66,7.73,7.80,7.86,7.92,7.98,8.03,8.09,8.14,8.19
7.0,3.34,4.16,4.68,5.06,5.36,5.61,5.82,6.00,6.16,6.30,...,7.24,7.30,7.36,7.42,7.48,7.53,7.58,7.63,7.68,7.73
8.0,3.26,4.04,4.53,4.89,5.17,5.40,5.60,5.77,5.92,6.05,...,6.93,6.99,7.05,7.11,7.16,7.21,7.26,7.31,7.35,7.40
9.0,3.20,3.95,4.41,4.76,5.02,5.24,5.43,5.59,5.74,5.87,...,6.70,6.76,6.82,6.87,6.92,6.97,7.02,7.06,7.10,7.14
10.0,3.15,3.88,4.33,4.65,4.91,5.12,5.30,5.46,5.60,5.72,...,6.53,6.58,6.63,6.69,6.73,6.78,6.82,6.87,6.91,6.95
11.0,3.11,3.82,4.26,4.57,4.82,5.03,5.20,5.35,5.49,5.61,...,6.38,6.44,6.49,6.54,6.58,6.63,6.67,6.71,6.75,6.79
12.0,3.08,3.77,4.20,4.51,4.75,4.95,5.12,5.27,5.39,5.51,...,6.26,6.32,6.37,6.41,6.46,6.50,6.54,6.58,6.62,6.66
13.0,3.06,3.73,4.15,4.45,4.69,4.88,5.05,5.19,5.32,5.43,...,6.17,6.22,6.26,6.31,6.36,6.40,6.44,6.48,6.52,6.55
14.0,3.03,3.70,4.11,4.41,4.64,4.83,4.99,5.13,5.25,5.36,...,6.08,6.13,6.18,6.22,6.27,6.31,6.35,6.39,6.42,6.46
15.0,3.01,3.67,4.08,4.37,4.59,4.78,4.94,5.08,5.20,5.31,...,6.01,6.06,6.10,6.15,6.19,6.23,6.27,6.31,6.34,6.38
16.0,3.00,3.65,4.05,4.33,4.56,4.74,4.90,5.03,5.15,5.26,...,5.95,5.99,6.04,6.08,6.13,6.17,6.20,6.24,6.28,6.31
17.0,2.98,3.63,4.02,4.30,4.52,4.70,4.86,4.99,5.11,5.21,...,5.89,5.94,5.98,6.03,6.07,6.11,6.14,6.18,6.22,6.25
18.0,2.97,3.61,4.00,4.28,4.49,4.67,4.82,4.96,5.07,5.17,...,5.84,5.89,5.93,5.98,6.02,6.06,6.09,6.13,6.16,6.20
19.0,2.96,3.59,3.98,4.25,4.47,4.65,4.79,4.92,5.04,5.14,...,5.80,5.85,5.89,5.93,5.97,6.01,6.05,6.08,6.11,6.15
20.0,2.95,3.58,3.96,4.23,4.45,4.62,4.77,4.90,5.01,5.11,...,5.76,5.81,5.85,5.89,5.93,5.97,6.00,6.04,6.07,6.10
21.0,2.94,3.56,3.94,4.21,4.42,4.60,4.74,4.87,4.98,5.08,...,5.73,5.77,5.81,5.85,5.89,5.93,5.97,6.00,6.03,6.07
22.0,2.93,3.55,3.93,4.20,4.41,4.58,4.72,4.85,4.96,5.06,...,5.69,5.74,5.78,5.82,5.86,5.90,5.93,5.97,6.00,6.03
23.0,2.93,3.54,3.91,4.18,4.39,4.56,4.70,4.83,4.94,5.03,...,5.67,5.71,5.75,5.79,5.83,5.87,5.90,5.93,5.97,6.00
24.0,2.92,3.53,3.90,4.17,4.37,4.54,4.68,4.81,4.92,5.01,...,5.64,5.68,5.72,5.76,5.80,5.84,5.87,5.91,5.94,5.97
25.0,2.91,3.52,3.89,4.15,4.36,4.53,4.67,4.79,4.90,4.99,...,5.62,5.66,5.70,5.74,5.78,5.81,5.85,5.88,5.91,5.94
26.0,2.91,3.51,3.88,4.14,4.35,4.51,4.65,4.77,4.88,4.98,...,5.59,5.64,5.68,5.72,5.75,5.79,5.82,5.85,5.89,5.92
27.0,2.90,3.51,3.87,4.13,4.33,4.50,4.64,4.76,4.86,4.96,...,5.57,5.61,5.66,5.69,5.73,5.77,5.80,5.83,5.86,5.89
28.0,2.90,3.50,3.86,4.12,4.32,4.49,4.62,4.74,4.85,4.94,...,5.55,5.60,5.64,5.67,5.71,5.75,5.78,5.81,5.84,5.87
29.0,2.89,3.49,3.85,4.11,4.31,4.47,4.61,4.73,4.84,4.93,...,5.54,5.58,5.62,5.66,5.69,5.73,5.76,5.79,5.82,5.85
30.0,2.89,3.49,3.85,4.10,4.30,4.46,4.60,4.72,4.82,4.92,...,5.52,5.56,5.60,5.64,5.67,5.71,5.74,5.77,5.80,5.83
31.0,2.88,3.48,3.84,4.09,4.29,4.45,4.59,4.71,4.81,4.90,...,5.50,5.54,5.58,5.62,5.66,5.69,5.72,5.76,5.79,5.82
32.0,2.88,3.48,3.83,4.09,4.28,4.45,4.58,4.70,4.80,4.89,...,5.49,5.53,5.57,5.61,5.64,5.68,5.71,5.74,5.77,5.80
33.0,2.88,3.47,3.83,4.08,4.28,4.44,4.57,4.69,4.79,4.88,...,5.48,5.52,5.56,5.59,5.63,5.66,5.69,5.73,5.76,5.78
34.0,2.87,3.47,3.82,4.07,4.27,4.43,4.56,4.68,4.78,4.87,...,5.46,5.50,5.54,5.58,5.61,5.65,5.68,5.71,5.74,5.77
35.0,2.87,3.46,3.81,4.07,4.26,4.42,4.56,4.67,4.77,4.86,...,5.45,5.49,5.53,5.57,5.60,5.64,5.67,5.70,5.73,5.76
36.0,2.87,3.46,3.81,4.06,4.25,4.41,4.55,4.66,4.76,4.85,...,5.44,5.48,5.52,5.55,5.59,5.62,5.66,5.69,5.72,5.74
37.0,2.87,3.45,3.80,4.05,4.25,4.41,4.54,4.66,4.76,4.85,...,5.43,5.47,5.51,5.54,5.58,5.61,5.64,5.67,5.70,5.73
38.0,2.86,3.45,3.80,4.05,4.24,4.40,4.53,4.65,4.75,4.84,...,5.42,5.46,5.50,5.53,5.57,5.60,5.63,5.66,5.69,5.72
39.0,2.86,3.45,3.79,4.04,4.24,4.39,4.53,4.64,4.74,4.83,...,5.41,5.45,5.49,5.52,5.56,5.59,5.62,5.65,5.68,5.71
40.0,2.86,3.44,3.79,4.04,4.23,4.39,4.52,4.63,4.73,4.82,...,5.40,5.44,5.48,5.51,5.55,5.58,5.61,5.64,5.67,5.70
41.0,2.86,3.44,3.79,4.03,4.23,4.38,4.51,4.63,4.73,4.82,...,5.39,5.43,5.47,5.50,5.54,5.57,5.60,5.63,5.66,5.69
42.0,2.85,3.44,3.78,4.03,4.22,4.38,4.51,4.62,4.72,4.81,...,5.38,5.42,5.46,5.50,5.53,5.56,5.59,5.62,5.65,5.68
43.0,2.85,3.43,3.78,4.03,4.22,4.37,4.50,4.62,4.72,4.80,...,5.37,5.41,5.45,5.49,5.52,5.55,5.58,5.61,5.64,5.67
44.0,2.85,3.43,3.78,4.02,4.21,4.37,4.50,4.61,4.71,4.80,...,5.37,5.41,5.44,5.48,5.51,5.55,5.58,5.61,5.64,5.66
45.0,2.85,3.43,3.77,4.02,4.21,4.36,4.49,4.61,4.70,4.79,...,5.36,5.40,5.44,5.47,5.51,5.54,5.57,5.60,5.63,5.66
46.0,2.85,3.42,3.77,4.01,4.20,4.36,4.49,4.60,4.70,4.79,...,5.35,5.39,5.43,5.46,5.50,5.53,5.56,5.59,5.62,5.65
47.0,2.85,3.42,3.77,4.01,4.20,4.36,4.48,4.60,4.69,4.78,...,5.35,5.39,5.42,5.46,5.49,5.52,5.55,5.58,5.61,5.64
48.0,2.84,3.42,3.76,4.01,4.20,4.35,4.48,4.59,4.69,4.78,...,5.34,5.38,5.42,5.45,5.48,5.52,5.55,5.58,5.61,5.63
49.0,2.84,3.42,3.76,4.00,4.19,4.35,4.48,4.59,4.69,4.77,...,5.33,5.37,5.41,5.44,5.48,5.51,5.54,5.57,5.60,5.63
50.0,2.84,3.42,3.76,4.00,4.19,4.34,4.47,4.58,4.68,4.77,...,5.33,5.37,5.40,5.44,5.47,5.50,5.53,5.56,5.59,5.62
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [196]:
## **Para el factor A**
I = 4; J = 3; n = 3
m1 = I - 2
n1 = I*J*(n-1)-2
print(m1,n1)

Tukey_A = TUKEY.iloc[n1, m1]*(MSE/(n*J))**(0.5)
Tukey_A

2 22

6.96710524935243

In [197]:
## **Para el factor B**
I = 4; J = 3; n = 3
m2 = J - 2
n2 = I*J*(n-1)-2
print(m2,n2)

Tukey_B = TUKEY.iloc[n2, m2]*(MSE/(n*I))**(0.5)
Tukey_B

1 22

5.46126312380264

In [198]:
HSD = Texttable()
HSD.add_rows ([['Tratamiento','valor absoluto diferencia Media', 'Tukey', 'HAY DIFERENCIAS: 1 = SI, 0 = NO','LINF', 'LSUP' ],
  ['A1-A2', abs((sum_A1-sum_A2)/9)	,	Tukey_A,	abs((sum_A1-sum_A2)/9)>Tukey_A, (sum_A1-sum_A2)/9-Tukey_A, (sum_A1-sum_A2)/9+Tukey_A],
  ['A1-A3', abs((sum_A1-sum_A3)/9)	,	Tukey_A,	abs((sum_A1-sum_A3)/9)>Tukey_A, (sum_A1-sum_A3)/9-Tukey_A, (sum_A1-sum_A3)/9+Tukey_A],
  ['A1-A4', abs((sum_A1-sum_A4)/9)	,	Tukey_A,	abs((sum_A1-sum_A4)/9)>Tukey_A, (sum_A1-sum_A4)/9-Tukey_A, (sum_A1-sum_A4)/9+Tukey_A],
  ['A2-A3', abs((sum_A2-sum_A3)/9)	,	Tukey_A,	abs((sum_A2-sum_A3)/9)>Tukey_A, (sum_A2-sum_A3)/9-Tukey_A, (sum_A2-sum_A3)/9+Tukey_A],
  ['A2-A4', abs((sum_A2-sum_A4)/9)	,	Tukey_A,	abs((sum_A2-sum_A4)/9)>Tukey_A, (sum_A2-sum_A4)/9-Tukey_A, (sum_A2-sum_A4)/9+Tukey_A],
  ['A3-A4', abs((sum_A3-sum_A4)/9)	,	Tukey_A,	abs((sum_A3-sum_A4)/9)>Tukey_A, (sum_A3-sum_A4)/9-Tukey_A, (sum_A3-sum_A4)/9+Tukey_A],
  ['B1-B2', abs((sum_B1-sum_B2)/12)	,	Tukey_B,	abs((sum_B1-sum_B2)/12)>Tukey_B, (sum_B1-sum_B2)/12-Tukey_B, (sum_B1-sum_B2)/12+Tukey_B],
  ['B1-B3', abs((sum_B1-sum_B3)/12)	,	Tukey_B,	abs((sum_B1-sum_B3)/12)>Tukey_B, (sum_B1-sum_B3)/12-Tukey_B, (sum_B1-sum_B3)/12+Tukey_B],
  ['B2-B3', abs((sum_B2-sum_B3)/12)	,	Tukey_B,	abs((sum_B2-sum_B3)/12)>Tukey_B, (sum_B2-sum_B3)/12-Tukey_B, (sum_B2-sum_B3)/12+Tukey_B]])
print(HSD.draw())

+-------------+------------------+-------+-----------------+---------+---------+
| Tratamiento |  valor absoluto  | Tukey |       HAY       |  LINF   |  LSUP   |
|             | diferencia Media |       | DIFERENCIAS: 1  |         |         |
|             |                  |       |  = SI, 0 = NO   |         |         |
+=============+==================+=======+=================+=========+=========+
| A1-A2       | 5                | 6.967 | 0               | -11.967 | 1.967   |
+-------------+------------------+-------+-----------------+---------+---------+
| A1-A3       | 13.111           | 6.967 | 1               | -20.078 | -6.144  |
+-------------+------------------+-------+-----------------+---------+---------+
| A1-A4       | 20.111           | 6.967 | 1               | -27.078 | -13.144 |
+-------------+------------------+-------+-----------------+---------+---------+
| A2-A3       | 8.111            | 6.967 | 1               | -15.078 | -1.144  |
+-------------+------------------+-------+-----------------+---------+---------+
| A2-A4       | 15.111           | 6.967 | 1               | -22.078 | -8.144  |
+-------------+------------------+-------+-----------------+---------+---------+
| A3-A4       | 7                | 6.967 | 1               | -13.967 | -0.033  |
+-------------+------------------+-------+-----------------+---------+---------+
| B1-B2       | 16               | 5.461 | 1               | -21.461 | -10.539 |
+-------------+------------------+-------+-----------------+---------+---------+
| B1-B3       | 22.250           | 5.461 | 1               | -27.711 | -16.789 |
+-------------+------------------+-------+-----------------+---------+---------+
| B2-B3       | 6.250            | 5.461 | 1               | -11.711 | -0.789  |
+-------------+------------------+-------+-----------------+---------+---------+